let num1 = 133;
let num2 = 45;

console.log(num1 + num2);

const result = num1 + num2;
console.log(result);

const sub = num1 - num2;
console.log(sub);

num1 = 500;
console.log(num1);
num2 = 150;
console.log(num2);

const sub2 = num2 * num1;
console.log(sub2);
// pratica de alteração de valor de uma variavel
num1 = 33;
num2 = 222;
console.log(num1 > num2);
console.log(num2 > num1);

num1 = '123'; //tipo string
num2 = 123; //tipo number

console.log(num1 === num2); //o correto para COMPARAR e usar tres sinais de =
console.log(num1 == num2); //no se usa dois sinais de = para comparar porque da verdadeira


 

