// [] isto é denominado como "array". Um array é um tipo especial de variável utilizado para armazenar uma coleção de dados, ou seja, armazenar múltiplas informações de uma só vez. O ideal é que as informações armazenadas em um array façam partes de um mesmo contexto, como por exemplo, uma lista de carros, uma lista de produtos, ou UFs de um estado.

// {} aqui usamos para stringTemplate
// () denominado como string "normal" texto corrido

// const arrayNumber = [1, 2, 3, 4, 5];
const arrayNumber = [10, 20, 30, 40, 50];

console.log(arrayNumber);

console.log(`O Valor elemento 0 da minha lista é ${arrayNumber[0]}`)
console.log(`O Valor elemento 1 da minha lista é ${arrayNumber[1]}`)
console.log(`O Valor elemento 2 da minha lista é ${arrayNumber[2]}`)
console.log(`O Valor elemento 3 da minha lista é ${arrayNumber[3]}`)
console.log(`O Valor elemento 4 da minha lista é ${arrayNumber[4]}`)